# Fucntions -> this are used to reuse the code 
# this will help us avoid duplicating the code 
def greet(name): # function signature -> name of function, parameters 
    # parameters/arguments 
    # parameters -> what you pass to the function ex: Bavitha, Sharukh 
    # arguments -> what the function accepts 
    # execute logic 
    # print the result or i can return so that users can 
    # utilize it 
    # print(f"Hi, {name}")
    # python will return None by default 
    # None mean no value returned 
    return f"Hi, {name}"

def get_name():
    print("Sharukh Khan")
    # when ever you want reuse the result generated by function 
    # you return the result from the function 
    # we return a value using a return keyword 
# calling a function 
# greet("Sharukh")
value = greet("Bavitha")
print(value)

# Variable Parameters in a function
# def add(num1,num2):
#     result = num1 + num2 
#     # print(result)
#     return result 
  
def add(*num):
    result = 0 
    for n in num:
        result += n 
    return result
# # 1,2,3 
# # 1 + 2 + 3 
# result = add(1,2)
# result = add(result,3)
# print(result)
# print(1,2,3,4,5)
nums = [1,2,3,4,5,6,7,8]
print(add(*nums))



# optional parameters 
def add(num1=0,num2=0):
    result = num1 + num2 
    # print(result)
    return result 
# print(1,2,3,4) # sep,end has given default values 
# print(add(1,2))
print(add(1))
